### ISSUE TITLE
Swift 3.1 support

### ISSUE THREAD

**Issue by saldous** [onmyway133/MainThreadGuard#3]
With xcode 8.3 and Swift 3.1 there is a build error:

Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

**Comment by onmyway133** [comment]
@saldous Hi, thanks for your report. I 've updated 2.1.0, in which we must call `Guard.setup()` directly, so users have more control where to use `Guard` or not. Hope you find this useful
