### ISSUE TITLE
support on Swift 5 and Ambiguous use of 'setNeedsDisplay'

### ISSUE THREAD

**Issue by devanshuwynk** [onmyway133/MainThreadGuard#4]
code needs to be updated for swift 5+
also while swizzling setNeedsDsiplay it is throwing **_Ambiguous use of 'setNeedsDisplay'_**

**Comment by onmyway133** [comment]
@devanshuwynk Hi, Xcode has this main thread guard feature so you don't need this lib

**Comment by devanshuwynk** [comment]
Oh, I am sorry. Thank you
